[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=chengmeiniu)](https://github.com/anuraghazra/github-readme-stats)


**Skills:**
<code><img height="32" src="https://cdn.jsdelivr.net/npm/simple-icons@v5/icons/r.svg"</code>
  
### Hi there 👋

<!--
**chengmeiniu/chengmeiniu** is a ✨ _special_ ✨ repository because its `README.md` (this file) appears on your GitHub profile.

Here are some ideas to get you started:

- 🔭 I’m currently working on ...
- 🌱 I’m currently learning ...
- 👯 I’m looking to collaborate on ...
- 🤔 I’m looking for help with ...
- 💬 Ask me about ...
- 📫 How to reach me: ...
- 😄 Pronouns: ...
- ⚡ Fun fact: ...
-->
<--
